name: auto sign
on:
  schedule:
    - cron: '0 1 * * *' # 每天1:00 UTC运行
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install requests datetime
    - name: Run script
      run: python main.py
